const app=document.getElementById('app');
const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)];
const services=[
 {path:'/seo/',num:'01',title:'تحسين محركات البحث SEO & GEO',short:'نرفع الظهور العضوي ونبني حضورًا مستدامًا في محركات البحث وتجارب البحث المدعومة بالذكاء الاصطناعي.',tag:'SEO',lead:'ظهور أقوى حين يبحث عميلك عن الحل.',intro:'نحوّل موقعك إلى أصل رقمي قابل للاكتشاف: بحث كلمات، بنية تقنية سليمة، محتوى يخدم نية البحث، سلطة موضوعية وقياس مستمر.',features:['Technical SEO Audit','Keyword & Intent Mapping','On-page SEO','Content Architecture','Digital PR & Authority','Local SEO','GEO / AI Search Readiness','Analytics & Reporting']},
 {path:'/digital-ads-2/',num:'02',title:'إدارة الحملات المدفوعة',short:'حملات أداء مبنية على البيانات عبر Google وMeta وTikTok وLinkedIn بهدف واضح وعائد قابل للقياس.',tag:'PERFORMANCE',lead:'كل ريال إعلاني له هدف ومسار ونتيجة.',intro:'نربط الاستراتيجية بالبيانات والإبداع لنصمم منظومة اكتساب عملاء من أول انطباع حتى التحويل، مع تحسين مستمر للميزانية والرسائل والجمهور.',features:['Media Strategy','Google Ads','Meta Ads','TikTok Ads','Creative Testing','Conversion Tracking','Landing Pages','ROAS Optimization']},
 {path:'/social-media/',num:'03',title:'إدارة حسابات التواصل الاجتماعي',short:'استراتيجية محتوى وصوت بصري متسق يحول الحسابات إلى قناة نمو وبناء مجتمع.',tag:'SOCIAL',lead:'حضور اجتماعي يَظهر، يُحفظ، ويُحرّك القرار.',intro:'نبدأ من شخصية العلامة والجمهور ثم نبني أعمدة المحتوى، التقويم، الإنتاج، النشر، إدارة المجتمع والتقارير الشهرية ضمن مسار واحد.',features:['Social Strategy','Content Calendar','Copywriting','Creative Production','Community Management','Short-form Video','Trend Adaptation','Monthly Reporting']},
 {path:'/website-dev/',num:'04',title:'تصميم وتطوير المواقع',short:'مواقع سريعة، متجاوبة، واضحة ومهيأة للتحويل ومحركات البحث من أول سطر كود.',tag:'WEB',lead:'موقعك ليس بروشورًا. هو أفضل موظف مبيعات لديك.',intro:'نصمم تجربة رقمية كاملة تبدأ من هيكلة المحتوى والـUX، ثم واجهة متفردة، تطوير نظيف، أداء قوي، SEO تقني وربط أدوات القياس.',features:['UX Architecture','UI Design System','Responsive Development','CMS Integration','Core Web Vitals','SEO Foundations','Analytics Setup','Ongoing Support']},
 {path:'/e-commerce-solutions/',num:'05',title:'حلول التجارة الإلكترونية',short:'متجر، دفع، شحن، تحليلات، تسويق وربط تقني يعمل كنظام تجاري واحد.',tag:'COMMERCE',lead:'متجر مصمم للبيع، لا لمجرد العرض.',intro:'نبني رحلة شراء تقلل الاحتكاك وتزيد التحويل، مع ربط المخزون والدفع والشحن والتحليلات والحملات لتصبح التجارة الإلكترونية قناة نمو قابلة للتوسع.',features:['Store Strategy','Shopify / WooCommerce','UX & CRO','Payment Integration','Shipping Integration','Product Architecture','Ecommerce SEO','Lifecycle Marketing']},
 {path:'/creatives-designs/',num:'06',title:'التصميم الجرافيكي والهوية',short:'نظام بصري مميز ومرن يثبت العلامة في ذهن الجمهور ويخدم كل نقاط الاتصال.',tag:'BRAND',lead:'الهوية القوية تُعرف قبل أن يُقرأ اسمها.',intro:'من الفكرة والموقف الاستراتيجي إلى الشعار، الألوان، الخطوط، الأنظمة البصرية وقوالب المحتوى، نصنع هوية قابلة للحياة والتوسع.',features:['Brand Strategy','Visual Identity','Logo Systems','Social Templates','Campaign Key Visuals','Presentation Design','Brand Guidelines','Creative Direction']},
 {path:'/motion-graphic/',num:'07',title:'الموشن جرافيك والفيديو',short:'فيديوهات قصيرة وموشن يشرح، يجذب ويحوّل الرسالة المعقدة إلى تجربة سهلة التذكر.',tag:'MOTION',lead:'اجعل رسالتك تتحرك قبل أن يتجاوزها المستخدم.',intro:'نطوّر الفكرة والسكريبت والـstoryboard والهوية الحركية ثم الإنتاج والمونتاج والصوت، مع نسخ مناسبة لكل منصة وحملة.',features:['Creative Concept','Scriptwriting','Storyboard','2D Motion','Product Videos','Short-form Edits','Sound Design','Platform Adaptation']},
 {path:'/mobile-application/',num:'08',title:'تصميم وتطوير تطبيقات الجوال',short:'تجارب تطبيقات واضحة وسريعة تربط المنتج بالعميل وتدعم النمو والاحتفاظ.',tag:'APPS',lead:'تطبيق يبدأ من حاجة حقيقية وينتهي بعادة استخدام.',intro:'نحوّل الفكرة إلى تدفقات استخدام، نماذج أولية، واجهة، تطوير واختبارات، مع اهتمام بالأداء والتحليلات وتجربة ما بعد الإطلاق.',features:['Product Discovery','UX Flows','UI Systems','Flutter / React Native','Native Integrations','QA & Testing','Analytics','Release Support']},
 {path:'/influencers-marketing/',num:'09',title:'التسويق عبر المؤثرين',short:'اختيار مؤثرين مناسبين للعلامة، إدارة التعاون وقياس الأثر بعيدًا عن الأرقام السطحية.',tag:'CREATORS',lead:'التأثير الحقيقي يبدأ من التطابق، لا من عدد المتابعين.',intro:'نحدد الجمهور والرسالة، نرشح المؤثرين حسب الجودة والملاءمة، ندير التفاوض والمحتوى والتتبع لنربط الانتشار بنتيجة تجارية.',features:['Creator Research','Audience Fit','Campaign Strategy','Negotiation','Briefing','Content Review','Tracking Links','Performance Report']}
];
const works=[
 ['NAWA','هوية وإطلاق رقمي','#0b1711','#b9ff56','#2c7d56'],['SAND','تجارة إلكترونية','#1a1633','#ffb95f','#8058ff'],['KIN','حملة أداء','#061b28','#54d7ff','#ff6a91'],['RISE','منصة رقمية','#2b120d','#ff885f','#ffe6c5'],['ORBIT','منتج تقني','#151515','#e8ff63','#7a6cff'],['HABIT','استراتيجية محتوى','#172112','#8fe66d','#e8d8a8']
];
const posts=[
 ['استراتيجية','كيف تبني منظومة تسويق لا تعتمد على قناة واحدة؟','الانتقال من حملات متفرقة إلى نظام نمو يربط المحتوى والبحث والإعلانات والتحويل.'],
 ['SEO','من SEO إلى GEO: ماذا يتغير في البحث المدعوم بالذكاء الاصطناعي؟','كيف تهيئ المحتوى والبنية والسلطة الموضوعية للظهور في تجارب البحث الجديدة.'],
 ['إعلانات','اختبار الإعلانات: لماذا الفكرة أهم من تغيير لون الزر؟','إطار عملي لاختبار الزوايا والرسائل والـhooks قبل الغرق في تفاصيل سطحية.'],
 ['تجارة إلكترونية','7 نقاط احتكاك تقتل التحويل في المتاجر','مراجعة عملية لمسار المنتج والسلة والدفع وما يمكن تحسينه سريعًا.'],
 ['براند','الهوية ليست شعارًا: كيف تبني نظامًا بصريًا قابلًا للتوسع؟','الفرق بين تصميم جميل وهوية تعمل عبر عشرات نقاط الاتصال.'],
 ['محتوى','كيف تحول خطة المحتوى إلى محرك طلب؟','ربط الموضوعات بنية العميل ومراحل القرار بدل النشر لمجرد الاستمرارية.']
];
function workCards(){return works.map((w,i)=>`<article class="work-card reveal" data-cat="${i%3===0?'brand':i%3===1?'web':'performance'}"><div class="work-art" style="--c:${w[2]};--a:${w[3]};--b:${w[4]}"></div><div class="work-info"><div><h3>${w[0]}</h3><span>${w[1]} · 2026</span></div><b>↗</b></div></article>`).join('')}
function serviceRows(){return services.map(s=>`<a class="service-row reveal" href="${s.path}" data-link><span class="num">${s.num}</span><h3>${s.title}</h3><p>${s.short}</p><span class="arrow">↗</span><i class="hover-tag"></i></a>`).join('')}
function marquee(){let t='STRATEGY ✦ PERFORMANCE ✦ SOCIAL ✦ SEO ✦ WEB ✦ BRAND ✦ E-COMMERCE ✦ MOTION ✦ ';return `<div class="marquee"><div class="marquee-track"><i>${t}</i><i>${t}</i><i>${t}</i><i>${t}</i></div></div>`}
function home(){return `
<section class="hero"><div class="hero-grid"></div><div class="hero-glow"></div><div class="hero-orb"></div><div class="hero-inner"><div class="hero-kicker"><p class="eyebrow light"><span></span> شريك نمو رقمي</p><span>RIYADH · CAIRO · EVERYWHERE</span></div><h1><span>نحوّل</span> <span class="outline">الانتباه</span><br>إلى <span class="lime">نمو.</span></h1><div class="hero-bottom"><p>نشار ديجيتال شريك استراتيجي يجمع بين الإبداع، البيانات والتقنية لبناء علامات أقوى، تجارب أفضل ونتائج يمكن قياسها.</p><div class="hero-actions"><a class="pill-btn magnetic" href="/contact-us/" data-link><span>احجز جلسة اكتشاف</span><b>↗</b></a><a class="ghost-btn" href="/portfolio/" data-link>شاهد الأعمال</a></div></div></div><div class="scroll-note">SCROLL TO EXPLORE ↓</div></section>
${marquee()}
<section class="section"><div class="container"><div class="section-head reveal"><div><p class="eyebrow"><span></span> من نحن</p></div><div><h2>لا نبيع خدمات منفصلة. نبني <em>نظام نمو.</em></h2><p>نبدأ من سؤال العمل الحقيقي، نفهم السوق والعميل، ثم نختار القنوات والأفكار والتقنيات التي تقرّبك من الهدف بدل ملء التقارير بالأرقام.</p></div></div><div class="about-split"><div class="visual-card reveal"><div class="rings"></div><h3>استراتيجية.<br>إبداع.<br><span style="color:var(--lime)">تنفيذ.</span></h3></div><div class="stats-stack reveal-stagger"><div class="stat-card"><strong>+120</strong><span>مشروعًا عبر قطاعات مختلفة</span></div><div class="stat-card"><strong>+9</strong><span>مسارات خدمة مترابطة</span></div><div class="stat-card"><strong>1</strong><span>فريق واحد مسؤول عن الصورة كاملة</span></div></div></div></div></section>
<section class="section services-dark"><div class="container"><div class="section-head reveal"><div><p class="eyebrow light"><span></span> الحلول</p></div><div><h2>كل ما يحتاجه حضورك <em>ليتحرك للأمام.</em></h2><p>من اكتشاف الفرصة إلى تنفيذها وتحسينها. فرق متخصصة تعمل على مسار واحد بدل جزر منفصلة.</p></div></div><div>${serviceRows()}</div><div style="margin-top:45px"><a class="pill-btn" href="/services/" data-link>كل الخدمات <b>↗</b></a></div></div></section>
<section class="section works"><div class="container"><div class="section-head reveal"><div><p class="eyebrow"><span></span> أعمال مختارة</p></div><div><h2>أعمال صُممت كي <em>تعمل.</em></h2><p>نماذج لهويات وتجارب وحملات نربط فيها الجمال بالوظيفة والنتيجة.</p></div></div><div class="work-grid">${workCards()}</div></div></section>
<section class="section"><div class="container"><div class="process-wrap"><div class="process-title reveal"><p class="eyebrow"><span></span> كيف نعمل</p><h2>وضوح قبل السرعة.</h2><p>عملية مرنة، لكن بلا قفز على الأساسيات.</p></div><div class="process-list"><div class="process-item reveal"><div><h3>نفهم ونحلل</h3><p>نراجع النشاط والسوق والعميل والمنافسين والبيانات الحالية. نحدد أين توجد الفرصة وأين يحدث الهدر.</p></div></div><div class="process-item reveal"><div><h3>نبني الاتجاه</h3><p>نحوّل التشخيص إلى استراتيجية: أهداف، رسائل، قنوات، تجربة، خطة محتوى، خطة قياس وأولويات واضحة.</p></div></div><div class="process-item reveal"><div><h3>ننطلق ونختبر</h3><p>ننتج ونطلق بسرعة محسوبة، ونبني فرضيات واختبارات على الأفكار والجمهور والرحلة بدل الاعتماد على التخمين.</p></div></div><div class="process-item reveal"><div><h3>نقيس ونضاعف</h3><p>نراقب الإشارات، نحدد ما يصنع الفرق، نقلص الهدر ونضاعف ما يعمل، مع تقرير يفهمه صاحب القرار.</p></div></div></div></div></div></section>
<div class="client-strip"><div class="client-track"><span>NORTH</span><span>KIN</span><span>ORBIT</span><span>SAND</span><span>NAWA</span><span>RISE</span><span>HABIT</span><span>NORTH</span><span>KIN</span><span>ORBIT</span><span>SAND</span><span>NAWA</span></div></div>
<section class="section"><div class="container"><div class="lead-panel reveal"><div><p class="eyebrow"><span></span> جلسة اكتشاف</p><h2>30 دقيقة قد تغيّر اتجاه الربع القادم.</h2><p>شاركنا الهدف والتحدي الحالي، وسنراجع معك أولويات النمو وما الذي يستحق أن يبدأ الآن وما الذي يمكن تأجيله.</p></div>${leadForm()}</div></div></section>
<section class="section testimonials"><div class="container"><div class="section-head reveal"><div><p class="eyebrow light"><span></span> من شركائنا</p></div><div><h2>الشراكة تُقاس بما <em>يتغير فعليًا.</em></h2></div></div><div class="quote-grid reveal-stagger"><article class="quote"><p>“الفريق جمع بين فهم البراند والأرقام. أصبح لدينا قرار أوضح بدل تشغيل قنوات منفصلة بدون رابط.”</p><footer><b>مدير تسويق</b><span>قطاع التجزئة</span></footer></article><article class="quote"><p>“أعدنا بناء الموقع والحملات كرحلة واحدة، والفرق ظهر في جودة العملاء قبل أن يظهر في حجم الزيارات.”</p><footer><b>مؤسس</b><span>B2B Services</span></footer></article><article class="quote"><p>“أكثر شيء مهم كان سرعة التعلم. كل شهر أصبح مبنيًا على ما تعلمناه في الشهر السابق.”</p><footer><b>مدير نمو</b><span>E-commerce</span></footer></article></div></div></section>`}
function leadForm(extra=''){return `<form class="form-grid js-form">${extra}<div class="field"><label>الاسم</label><input required name="name" placeholder="اسمك"></div><div class="field"><label>رقم الجوال</label><input required name="phone" inputmode="tel" placeholder="05xxxxxxxx"></div><div class="field full"><label>ما الذي تريد تطويره؟</label><select name="service"><option>اختر الخدمة</option>${services.map(s=>`<option>${s.title}</option>`).join('')}</select></div><button class="submit-btn" type="submit">أرسل الطلب ↗</button></form>`}
function pageHero(title,desc,ey='نشار ديجيتال',art=false){return `<section class="page-hero"><div class="container"><div class="breadcrumb">الرئيسية / ${ey}</div><h1>${title}</h1>${desc?`<p>${desc}</p>`:''}</div>${art?'<div class="service-hero-art"></div>':''}</section>`}
function about(){return `${pageHero('نحن نعمل عند تقاطع <em>الإبداع والنمو.</em>','فريق متعدد التخصصات يربط ما تقوله العلامة بما يراه العميل وما تقيسه الأرقام.','من نحن')}
<section class="section"><div class="container"><div class="section-head reveal"><div><p class="eyebrow"><span></span> قصتنا</p></div><div><h2>الفرق ليس في الأدوات. الفرق في <em>طريقة التفكير.</em></h2><p>ظهرت نشار من ملاحظة بسيطة: كثير من الشركات تملك وكالة محتوى، شخص إعلانات، مطورًا، ومستشار SEO، لكن لا أحد يملك الصورة كاملة. لذلك بنينا فريقًا يعمل حول هدف واحد لا حول تخصصه فقط.</p></div></div><div class="about-split"><div class="visual-card reveal"><div class="rings"></div><h3>نحلم.<br>نبني.<br><span style="color:var(--lime)">نقيس.</span></h3></div><div class="stats-stack reveal-stagger"><div class="stat-card"><strong>01</strong><span>شريك واحد بدل خمسة موردين</span></div><div class="stat-card"><strong>02</strong><span>قرار مبني على البيانات والسياق</span></div><div class="stat-card"><strong>03</strong><span>إبداع يخدم هدفًا تجاريًا</span></div></div></div></div></section>
<section class="feature-band"><div class="feature-grid"><h2 class="reveal">القيم التي تحكم طريقة عملنا.</h2><div class="feature-list reveal-stagger"><div>الوضوح قبل الإبهار</div><div>العميل قبل المنصة</div><div>القياس قبل الادعاء</div><div>البساطة بعد العمق</div><div>سرعة التعلم لا سرعة النشر فقط</div><div>شراكة تتحدث بلغة العمل</div></div></div></section>
<section class="section"><div class="container"><div class="process-wrap"><div class="process-title reveal"><p class="eyebrow"><span></span> مهمتنا</p><h2>نقرب المسافة بين الطموح والنتيجة.</h2></div><div class="process-list"><div class="process-item reveal"><div><h3>فهم الأعمال</h3><p>لا نبدأ من “ماذا سننشر؟” بل من “ماذا يجب أن يتغير في العمل؟”.</p></div></div><div class="process-item reveal"><div><h3>تجربة العميل</h3><p>نقرأ كل نقطة تواصل كجزء من رحلة واحدة، من أول بحث أو إعلان حتى ما بعد الشراء.</p></div></div><div class="process-item reveal"><div><h3>نظام قابل للتطوير</h3><p>نبني أصولًا وعمليات تسمح بالنمو بدل نتائج قصيرة العمر تحتاج البدء من الصفر كل مرة.</p></div></div></div></div></div></section>`}
function servicesPage(){return `${pageHero('حلول رقمية تدفع <em>العمل للأمام.</em>','خدمات مترابطة تبدأ من الاستراتيجية وتصل إلى التنفيذ، القياس والتحسين.','الخدمات',true)}<section class="section services-dark"><div class="container"><div>${serviceRows()}</div></div></section><section class="section"><div class="container"><div class="lead-panel reveal"><div><p class="eyebrow"><span></span> لست متأكدًا من البداية؟</p><h2>ابدأ بالمشكلة، وليس باسم الخدمة.</h2><p>أخبرنا بالهدف والتحدي، وسنقترح التركيبة التي تحتاجها بدل دفعك إلى باقة جاهزة.</p></div>${leadForm()}</div></div></section>`}
function servicePage(s){return `${pageHero(`${s.title.split(' ').slice(0,-1).join(' ')} <em>${s.title.split(' ').slice(-1)}</em>`,s.lead,s.tag,true)}<section class="section"><div class="container"><div class="section-head reveal"><div><p class="eyebrow"><span></span> ما الذي نفعله؟</p></div><div><h2>${s.intro}</h2></div></div><div class="icon-grid reveal-stagger">${s.features.slice(0,6).map((f,i)=>`<article class="icon-card"><div class="icon">0${i+1}</div><h3>${f}</h3><p>تنفيذ عملي داخل خطة واحدة مع مؤشرات واضحة، مراجعات دورية وتوثيق لما نتعلمه ونحسنه.</p></article>`).join('')}</div></div></section><section class="feature-band"><div class="feature-grid"><h2 class="reveal">ما تحصل عليه ضمن المسار.</h2><div class="feature-list reveal-stagger">${s.features.map(f=>`<div>${f}</div>`).join('')}</div></div></section><section class="section"><div class="container"><div class="process-wrap"><div class="process-title reveal"><p class="eyebrow"><span></span> المنهج</p><h2>من التشخيص إلى التحسين.</h2></div><div class="process-list"><div class="process-item reveal"><div><h3>Discovery & Audit</h3><p>فهم الوضع الحالي، الأهداف، السوق، الجمهور والبيانات المتاحة.</p></div></div><div class="process-item reveal"><div><h3>Strategy & Build</h3><p>بناء خارطة الطريق والأصول المطلوبة وتهيئة القياس قبل الإطلاق.</p></div></div><div class="process-item reveal"><div><h3>Launch & Learn</h3><p>إطلاق مرحلي، جمع إشارات حقيقية وتحويلها إلى قرارات تحسين.</p></div></div><div class="process-item reveal"><div><h3>Scale</h3><p>مضاعفة ما يثبت نجاحه وتطوير المنظومة حسب نمو العمل.</p></div></div></div></div></div></section><section class="section"><div class="container"><div class="lead-panel reveal"><div><p class="eyebrow"><span></span> ابدأ الآن</p><h2>هل هذه الخدمة مناسبة لهدفك؟</h2><p>احجز جلسة قصيرة وسنساعدك على تحديد النطاق والأولوية والخطوة العملية التالية.</p></div>${leadForm()}</div></div></section>`}
function portfolio(){return `${pageHero('أعمال تتحول من فكرة إلى <em>أثر.</em>','مختارات من مشاريع براند، مواقع، تجارة إلكترونية وحملات أداء.','أعمالنا')}<section class="section portfolio-page"><div class="container"><div class="filter-row"><button class="active" data-filter="all">الكل</button><button data-filter="brand">هوية</button><button data-filter="web">ويب</button><button data-filter="performance">أداء</button></div><div class="work-grid">${workCards()}</div></div></section>`}
function blog(){return `${pageHero('أفكار قابلة للاستخدام، لا <em>للحفظ فقط.</em>','ملاحظات عملية حول التسويق، النمو، البحث، الإبداع وتجربة العميل.','المدونة')}<section class="section"><div class="container"><div class="blog-grid">${posts.map((p,i)=>`<article class="post-card reveal"><div class="post-art"></div><div class="meta">${p[0]} · ${10+i} دقائق قراءة</div><h3>${p[1]}</h3><p>${p[2]}</p><a href="/blog/${i+1}/" data-link>اقرأ المقال ↗</a></article>`).join('')}</div></div></section>`}
function article(id){let p=posts[(+id-1)%posts.length]||posts[0];return `${pageHero(`${p[1]}`,'مقال من نشار ديجيتال حول بناء قرارات تسويقية أكثر وضوحًا.','المدونة')}<section class="section"><article class="legal"><p class="eyebrow"><span></span> ${p[0]} · 2026</p><h2>لماذا هذا الموضوع مهم؟</h2><p>${p[2]} الفكرة الأساسية هي أن القنوات ليست الاستراتيجية، والأدوات ليست الخطة. يجب أن يبدأ القرار من فهم العميل والهدف والقيود الحقيقية.</p><h2>ابدأ من التشخيص</h2><p>اجمع البيانات التي توضح أين تضيع الفرص اليوم: ما مصدر الطلب؟ أين يتوقف المستخدم؟ ما الرسائل التي تنجح؟ وما الذي يصعب قياسه؟ عندما يصبح التشخيص واضحًا يصبح اختيار التكتيك أبسط.</p><h2>حوّل الافتراضات إلى اختبارات</h2><p>بدل تغيير عشرة أشياء معًا، اكتب فرضية محددة، حدد الإشارة التي ستثبتها أو تنفيها، ثم نفذ اختبارًا يمكن قراءته. بهذه الطريقة يتحول التسويق إلى تراكم معرفة لا سلسلة محاولات منفصلة.</p><h2>ابنِ ما يمكن تكراره</h2><p>الهدف النهائي ليس حملة ناجحة فقط، بل نظام يمكنه إنتاج نتائج وتعلم جديد بصورة متكررة. وثق ما يعمل، حسّن العملية وشارك المعرفة بين الفرق.</p></article></section>`}
function contact(){return `${pageHero('ابدأ المحادثة التي قد تغيّر <em>المسار.</em>','شاركنا ما تريد تحقيقه، وسنرد عليك بخطوة عملية واضحة.','تواصل معنا')}<section class="section"><div class="container contact-grid"><div class="contact-info reveal"><p class="eyebrow"><span></span> تواصل</p><h2>مشروع جديد، تحدٍ قائم أو فكرة تحتاج اختبارًا؟</h2><div class="contact-line"><span>البريد</span><b>hello@nashar.digital</b></div><div class="contact-line"><span>الموقع</span><b>الرياض · القاهرة · عن بُعد</b></div><div class="contact-line"><span>الرد</span><b>خلال يوم عمل</b></div></div><div class="contact-form reveal">${leadForm('<div class="field full"><label>الشركة / العلامة</label><input name="company" placeholder="اسم الشركة"></div><div class="field full"><label>أخبرنا بالتحدي</label><textarea name="message" placeholder="ما الذي تريد تحقيقه؟"></textarea></div>')}</div></div></section>`}
function faq(){let qs=[['كيف تبدأون مشروعًا جديدًا؟','نبدأ بجلسة اكتشاف لفهم الهدف والسياق. بعدها نرسل نطاق عمل واضحًا يتضمن الأولويات والمخرجات وطريقة القياس.'],['هل يمكن طلب خدمة واحدة فقط؟','نعم. يمكن العمل على مسار واحد عندما يكون ذلك منطقيًا، أو ربط أكثر من خدمة عندما تكون المشكلة تحتاج منظومة متكاملة.'],['هل تعملون مع شركات خارج السعودية؟','نعم، طريقة العمل مرنة وتسمح بالتعاون عن بعد مع شركات في المنطقة وخارجها.'],['هل تقدمون تقارير شهرية؟','نعم، لكننا نركز على تفسير ما تعنيه الأرقام والقرارات الناتجة عنها، لا مجرد إرسال لوحات بيانات.'],['هل يمكن تطوير موقع أو متجر موجود بدل بنائه من الصفر؟','نعم. نراجع الوضع الحالي أولًا ثم نحدد هل التطوير الجزئي منطقي أم أن إعادة البناء ستعطي عائدًا أفضل.'],['كيف يتم تسعير المشاريع؟','حسب نطاق العمل، حجم الإنتاج، القنوات، التعقيد التقني ومدة التعاون. بعد جلسة الاكتشاف نقدم عرضًا مفصلًا.']];return `${pageHero('أسئلة واضحة. <em>إجابات أوضح.</em>','أكثر ما نسأل عنه قبل بدء التعاون.','الأسئلة الشائعة')}<section class="section"><div class="container"><div class="faq-list">${qs.map((q,i)=>`<div class="faq-item ${i===0?'open':''}"><button class="faq-q"><span>${q[0]}</span><b>+</b></button><div class="faq-a"><p>${q[1]}</p></div></div>`).join('')}</div></div></section>`}
function careers(){return `${pageHero('ابنِ معنا ما يستحق <em>الانتباه.</em>','نبحث عن أشخاص يحبون الفكرة القوية والتنفيذ المنضبط والتعلم السريع.','الوظائف')}<section class="section"><div class="container"><div class="section-head reveal"><div><p class="eyebrow"><span></span> فرص مفتوحة</p></div><div><h2>اعمل مع فريق يرى الصورة كاملة.</h2><p>بيئة عمل مرنة، مسؤولية حقيقية وفرصة للعمل على تحديات متنوعة عبر البراند، الأداء والمنتج.</p></div></div><div class="career-list"><div class="job"><h3>Senior Performance Marketer</h3><span>Hybrid · Full time</span><a href="mailto:careers@nashar.digital">↗</a></div><div class="job"><h3>Arabic Copywriter</h3><span>Remote · Full time</span><a href="mailto:careers@nashar.digital">↗</a></div><div class="job"><h3>Motion Designer</h3><span>Remote · Project based</span><a href="mailto:careers@nashar.digital">↗</a></div></div></div></section>`}
function privacy(){return `${pageHero('سياسة <em>الخصوصية.</em>','نلتزم بجمع الحد الأدنى اللازم من البيانات واستخدامه بصورة واضحة.','الخصوصية')}<section class="section"><article class="legal"><p>آخر تحديث: أغسطس 2026</p><h2>البيانات التي نجمعها</h2><p>قد نجمع المعلومات التي ترسلها طوعًا عبر نماذج التواصل، مثل الاسم ورقم الجوال والبريد ومعلومات الشركة، بالإضافة إلى بيانات استخدام تقنية أساسية عند تفعيل أدوات التحليلات.</p><h2>كيف نستخدم البيانات</h2><p>نستخدم المعلومات للرد على الاستفسارات، تقديم الخدمات، تحسين تجربة الموقع، قياس الأداء والامتثال للمتطلبات النظامية ذات الصلة.</p><h2>المشاركة والحفظ</h2><p>لا نبيع بيانات المستخدمين. قد نستخدم مزودي خدمات تقنيين بالقدر اللازم لتشغيل الموقع والخدمات مع تطبيق ضوابط مناسبة.</p><h2>حقوقك</h2><p>يمكنك طلب الوصول إلى بياناتك أو تصحيحها أو حذفها وفق ما تسمح به الأنظمة المعمول بها عبر مراسلتنا على hello@nashar.digital.</p></article></section>`}
function en(){document.documentElement.lang='en';document.documentElement.dir='ltr';return `<section class="hero"><div class="hero-grid"></div><div class="hero-glow"></div><div class="hero-orb"></div><div class="hero-inner"><div class="hero-kicker"><p class="eyebrow light"><span></span> DIGITAL GROWTH PARTNER</p><span>RIYADH · CAIRO · EVERYWHERE</span></div><h1>TURNING <span class="outline">ATTENTION</span><br>INTO <span class="lime">GROWTH.</span></h1><div class="hero-bottom"><p>Nashar Digital brings strategy, creativity, data and technology together to build stronger brands and measurable growth systems.</p><div class="hero-actions"><a class="pill-btn" href="/contact-us/" data-link><span>Start a project</span><b>↗</b></a><a class="ghost-btn" href="/portfolio/" data-link>Selected work</a></div></div></div></section>${marquee()}<section class="section"><div class="container"><div class="section-head reveal"><div><p class="eyebrow"><span></span> WHAT WE DO</p></div><div><h2>One partner for the <em>whole growth system.</em></h2><p>Strategy, performance, social, SEO, web, commerce and brand — connected around one business goal.</p></div></div><div class="icon-grid">${['Strategy','Performance','SEO & GEO','Web & Commerce','Brand & Creative','Social & Content'].map((x,i)=>`<div class="icon-card reveal"><div class="icon">0${i+1}</div><h3>${x}</h3><p>Focused execution, clear measurement and continuous learning.</p></div>`).join('')}</div></div></section>`}
function notFound(){return `<section class="not-found"><b>404</b><h1>الصفحة غير موجودة</h1><p>ربما تغير الرابط أو تم نقله.</p><a class="pill-btn" href="/" data-link>العودة للرئيسية ↗</a></section>`}
function resolve(path){let p=path.replace(/\/+/g,'/');if(p==='')p='/';if(p==='/')return home();if(p==='/about-us/')return about();if(p==='/services/'||decodeURI(p).includes('خدماتنا'))return servicesPage();if(p==='/portfolio/'||decodeURI(p).includes('أعمالنا'))return portfolio();if(p==='/blog/'||p==='/our-blog/')return blog();if(p==='/contact-us/')return contact();if(p==='/faq/')return faq();if(p==='/careers/')return careers();if(p==='/privacy-policy/')return privacy();if(p==='/en/')return en();let s=services.find(x=>x.path===p);if(s)return servicePage(s);let m=p.match(/^\/blog\/(\d+)\/?$/);if(m)return article(m[1]);return notFound()}
function render(path=location.pathname,{push=false}={}){if(push)history.pushState({},'',path);if(path!='/en/'){document.documentElement.lang='ar';document.documentElement.dir='rtl'}app.innerHTML=resolve(path);window.scrollTo(0,0);setTitle(path);bindDynamic();requestAnimationFrame(()=>observeReveals())}
function setTitle(path){let s=services.find(x=>x.path===path);let t=s?s.title:path==='/about-us/'?'من نحن':path==='/services/'?'الخدمات':path==='/portfolio/'?'أعمالنا':path==='/blog/'?'المدونة':path==='/contact-us/'?'تواصل معنا':path==='/faq/'?'الأسئلة الشائعة':path==='/careers/'?'الوظائف':path==='/privacy-policy/'?'سياسة الخصوصية':path==='/en/'?'Nashar Digital | Growth Partner':'نشار ديجيتال | شريك النمو الرقمي';document.title=`${t}${path==='/'||path==='/en/'?'':' | نشار ديجيتال'}`}
function bindDynamic(){
 $$('.js-form').forEach(f=>f.addEventListener('submit',e=>{e.preventDefault();showToast('تم استلام طلبك — سنتواصل معك قريبًا.');f.reset()}));
 $$('.faq-q').forEach(b=>b.onclick=()=>b.parentElement.classList.toggle('open'));
 $$('.filter-row button').forEach(b=>b.onclick=()=>{$$('.filter-row button').forEach(x=>x.classList.remove('active'));b.classList.add('active');let v=b.dataset.filter;$$('.work-card').forEach(c=>c.style.display=v==='all'||c.dataset.cat===v?'':'none')});
 bindLinks();
}
function bindLinks(){$$('a[data-link]').forEach(a=>{if(a.dataset.bound)return;a.dataset.bound='1';a.addEventListener('click',e=>{let u=new URL(a.href,location.origin);if(u.origin===location.origin){e.preventDefault();closeMenu();render(u.pathname,{push:true})}})})}
function observeReveals(){let io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}}),{threshold:.12});$$('.reveal,.reveal-stagger').forEach(x=>io.observe(x))}
function showToast(msg){let t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3500)}
function closeMenu(){document.body.classList.remove('menu-open');$('#mobileMenu').classList.remove('open');$('#mobileMenu').setAttribute('aria-hidden','true');$('#menuToggle').setAttribute('aria-expanded','false')}
$('#menuToggle').addEventListener('click',()=>{let open=!document.body.classList.contains('menu-open');document.body.classList.toggle('menu-open',open);$('#mobileMenu').classList.toggle('open',open);$('#mobileMenu').setAttribute('aria-hidden',String(!open));$('#menuToggle').setAttribute('aria-expanded',String(open))});
window.addEventListener('popstate',()=>render(location.pathname));
window.addEventListener('scroll',()=>{let y=scrollY,h=document.documentElement.scrollHeight-innerHeight;$('#siteHeader').classList.toggle('scrolled',y>30);$('#page-progress').style.width=(h?y/h*100:0)+'%'},{passive:true});
if(matchMedia('(pointer:fine)').matches){let d=$('.cursor-dot'),r=$('.cursor-ring'),x=0,y=0,rx=0,ry=0;window.addEventListener('mousemove',e=>{x=e.clientX;y=e.clientY;d.style.transform=`translate(${x}px,${y}px) translate(-50%,-50%)`});(function loop(){rx+=(x-rx)*.14;ry+=(y-ry)*.14;r.style.transform=`translate(${rx}px,${ry}px) translate(-50%,-50%)`;requestAnimationFrame(loop)})();document.addEventListener('mouseover',e=>{if(e.target.closest('a,button,input,select,textarea')){r.style.width='54px';r.style.height='54px'}});document.addEventListener('mouseout',e=>{if(e.target.closest('a,button,input,select,textarea')){r.style.width='34px';r.style.height='34px'}})}
document.addEventListener('mousemove',e=>{$$('.magnetic').forEach(el=>{let b=el.getBoundingClientRect(),dx=e.clientX-(b.left+b.width/2),dy=e.clientY-(b.top+b.height/2),near=Math.abs(dx)<b.width&&Math.abs(dy)<b.height;if(near)el.style.transform=`translate(${dx*.12}px,${dy*.12}px)`;else el.style.transform=''})});
$('#year').textContent=new Date().getFullYear();render(location.pathname);